[package]
name = "rust-chip-8"
version = "0.1.0"
authors = ["Elijah"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
minifb = "0.19.2"